// <auto-generated />
using System;
using DatabasesProgrammingExample01.Database.EFCoreUserWithFriends;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabasesProgrammingExample01.Migrations
{
    [DbContext(typeof(EFCoreUserWithFriendsContext))]
    [Migration("20230108125248_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabasesProgrammingExample01.Models.UserWithFriends", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DatabasesProgrammingExample01.Models.UserWithFriendsJoin", b =>
                {
                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("FriendId")
                        .HasColumnType("int");

                    b.Property<int?>("UserWithFriendsId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "FriendId");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserWithFriendsId");

                    b.ToTable("UserWithFriendsJoin");
                });

            modelBuilder.Entity("DatabasesProgrammingExample01.Models.UserWithFriendsJoin", b =>
                {
                    b.HasOne("DatabasesProgrammingExample01.Models.UserWithFriends", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabasesProgrammingExample01.Models.UserWithFriends", "User")
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabasesProgrammingExample01.Models.UserWithFriends", null)
                        .WithMany("FriendsWith")
                        .HasForeignKey("UserWithFriendsId");

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DatabasesProgrammingExample01.Models.UserWithFriends", b =>
                {
                    b.Navigation("Friends");

                    b.Navigation("FriendsWith");
                });
#pragma warning restore 612, 618
        }
    }
}
